name: ai_descriptor
description: AI Product Description Generator
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.2.0
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  provider: ^6.1.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon1.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
  assets:
    - .env
    - assets/icon/
    - assets/fonts/Inter/static/